// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthOps struct {
	Login    interface{} `json:"login" bson:"login"`
	Register interface{} `json:"register" bson:"register"`
}

type FilterItem struct {
	NameItem    *string `json:"name_item" bson:"name_item"`
	Stock       *int    `json:"stock" bson:"stock"`
	Description *string `json:"description" bson:"description"`
	Price       *int    `json:"price" bson:"price"`
}

type Item struct {
	ID          string `json:"id" bson:"_id"`
	NameItem    string `json:"name_item" bson:"name_item"`
	Stock       int    `json:"stock" bson:"stock"`
	Description string `json:"description" bson:"description"`
	Price       int    `json:"price" bson:"price"`
}

type NewItem struct {
	NameItem    string `json:"name_item" bson:"name_item"`
	Stock       int    `json:"stock" bson:"stock"`
	Description string `json:"description" bson:"description"`
	Price       int    `json:"price" bson:"price"`
}

type NewUser struct {
	Name     string `json:"name" bson:"name"`
	Email    string `json:"email" bson:"email"`
	Password string `json:"password" bson:"password"`
}

type User struct {
	ID       string  `json:"id" bson:"_id"`
	Name     string  `json:"name" bson:"name"`
	Email    string  `json:"email" bson:"email"`
	Password *string `json:"password" bson:"password"`
}

type CredsLogin struct {
	Email    string `json:"email" bson:"email"`
	Password string `json:"password" bson:"password"`
}
